export const menuFormData={
    restaurantName:"",
    restaurantLogo:null,
    backgroundCard:"#000",
    backgroundTemplates:[{
        imgTemplate:null
    }],
    category:[{
        categoryName:"",
        products:[{
            backgroundProductCard:"#fff",
            colorName:"#000",
            colorDescription:"#000",
            colorPrice:"#000",
            productImg:null,
            productName:"",
            productDescription:"",
            top:false,
            price:null
        }]
    }]
}