export const menuFormData={
    restaurantName:"",
    restaurantLogo:null,
    backgroundCard:"#000",
    colorMenu:'#fff',
    fontFamily:'38aaa491-5385-4ebf-b0a5-6d718ddf9052',
    userTemplate:null,
    imgTemplate:null,
    category:[{
        categoryName:"",
        products:[{
            backgroundProductCard:"#fff",
            colorName:"#000",
            colorDescription:"#000",
            colorPrice:"#000",
            productImg:null,
            productName:"",
            productDescription:"",
            top:false,
            price:null
        }]
    }]
}