export const menuFormData={
    restaurantName:"",
    restaurantLogo:null,
    backgroundCard:"#000",
    backgroundTemplates:[{
        imgTemplate:null
    }],
    category:[{
        categoryName:"",
        products:[{
            backgroundProductCard:"#fff",
            colorName:"#fff",
            colorDescription:"#fff",
            colorPrice:"#fff",
            productImg:null,
            productName:"",
            productDescription:"",
            top:false,
            price:null
        }]
    }]
}